// resources/js/components/CustomerSelect.vue
<template>
    <select ref="selectRef" :placeholder="placeholder" autocomplete="off" class="w-full"></select>
</template>

<script setup>
import { ref, onMounted, onBeforeUnmount, watch } from 'vue'
import axios from 'axios'

const props = defineProps({
    modelValue: [String, Number],
    placeholder: {
        type: String,
        default: 'Search customer...'
    },
    valueField: {
        type: String,
        default: 'id'
    },
    labelField: {
        type: String,
        default: 'name'
    },
    initialData: {
        type: Object,
        default: null
    }
})

const emit = defineEmits(['update:modelValue', 'change', 'selected'])

const selectRef = ref(null)
let tomSelect = null

const initTomSelect = () => {
    if (typeof window.TomSelect === 'undefined') return

    tomSelect = new window.TomSelect(selectRef.value, {
        valueField: props.valueField,
        labelField: props.labelField,
        searchField: ['name', 'mobile', 'email'],
        load: function(query, callback) {
            axios.get('/account/list', {
                params: {
                    query: query,
                    model: 'customer'
                }
            })
            .then(response => {
                callback(response.data.items || []);
            })
            .catch(() => {
                callback();
            });
        },
        render: {
            option: function(data, escape) {
                return `<div>
                    <div class="font-medium">${escape(data.name)}</div>
                    <div class="text-gray-400 text-xs">${escape(data.mobile || '')} ${data.email ? '• ' + escape(data.email) : ''}</div>
                </div>`;
            },
            item: function(data, escape) {
                return `<div>${escape(data.name)} ${data.mobile ? '<span class="text-gray-500 ml-1">(' + escape(data.mobile) + ')</span>' : ''}</div>`;
            }
        },
        onChange: (value) => {
            emit('update:modelValue', value);
            const selected = tomSelect.options[value];
            emit('change', value, selected);
            if (selected) {
                emit('selected', selected);
            }
        }
    });

    // Handle initial value
    if (props.initialData) {
        tomSelect.addOption(props.initialData);
        tomSelect.setValue(props.modelValue, true);
    } else if (props.modelValue && props.valueField === 'name') {
        // Fallback for name-based selection without full data
        tomSelect.addOption({ name: props.modelValue });
        tomSelect.setValue(props.modelValue, true);
    }
}

onMounted(() => {
    if (typeof window.TomSelect !== 'undefined') {
        initTomSelect()
    } else {
        const check = setInterval(() => {
            if (typeof window.TomSelect !== 'undefined') {
                clearInterval(check)
                initTomSelect()
            }
        }, 100)
    }
})

onBeforeUnmount(() => {
    if (tomSelect) tomSelect.destroy()
})

watch(() => props.modelValue, (val) => {
    if (tomSelect && val !== tomSelect.getValue()) {
        if (val && !tomSelect.options[val]) {
            // Option doesn't exist, add it from initialData if available
            if (props.initialData && props.initialData.id === val) {
                tomSelect.addOption(props.initialData)
            }
        }
        tomSelect.setValue(val, true)
    }
})

// Watch initialData changes to update TomSelect accordingly
watch(() => props.initialData, (newData) => {
    if (tomSelect && newData && newData.id) {
        // Add or update the option
        tomSelect.addOption(newData)
        // Set value if it matches the modelValue
        if (newData.id === props.modelValue) {
            tomSelect.setValue(newData.id, true)
        }
    }
}, { deep: true })
</script>

<style>
/* Base TomSelect overrides can go here or in a global file */
.ts-wrapper .ts-control {
    border-radius: 0.5rem;
    padding: 0.5rem 0.75rem;
}
</style>

// resources/js/react/Pages/SaleReturn/Components/CustomerSelect.jsx
import React, { useEffect, useRef, useState } from "react";
import TomSelect from "tom-select";
import axios from "axios";

export default function CustomerSelect({ value, onChange, newCustomer }) {

    const selectRef = useRef(null);
    const tomRef = useRef(null);
    const [options, setOptions] = useState([]);

    // Load initial customers
    useEffect(() => {
        let mounted = true;

        axios.get("/account/list").then(res => {
            if (!mounted) return;
            const customers = (res.data.items || []).map(c => ({
                id: String(c.id),
                name: `${c.name} (${c.mobile || "-"})`,
            }));
            setOptions(customers);
        });

        return () => { mounted = false; };
    }, []);

    // Initialize TomSelect
    useEffect(() => {
        if (!selectRef.current) return;

        // Destroy previous instance
        tomRef.current?.destroy();

        tomRef.current = new TomSelect(selectRef.current, {
            valueField: "id",
            labelField: "name",
            searchField: ["name"],
            options,
            maxItems: 1,
            create: true,
            load: function(query, callback) {
                if (!query.length) return callback(options);
                axios.get("/account/list", { params: { query } })
                    .then(res => {
                        const data = (res.data.items || []).map(c => ({
                            id: String(c.id),
                            name: `${c.name} (${c.mobile || "-"})`,
                        }));
                        callback(data);
                    })
                    .catch(() => callback());
            },
            onChange(val) {
                if (val) onChange?.(Number(val));
                else onChange?.(null);
            },
        });

        

        // Auto-select in edit mode
        if (value) {
            const existing = options.find(o => o.id === String(value));
            if (existing) {
                tomRef.current.setValue(existing.id, true);
            } else {
                // Fetch the customer and add to options
                axios.get(`/account/${value}`).then(res => {
                    const sel = { id: String(res.data.id), name: `${res.data.name} (${res.data.mobile || "-"})` };
                    setOptions(prev => [sel, ...prev]); // prepend to options
                    tomRef.current.addOption(sel);
                    tomRef.current.setValue(sel.id, true);
                });
            }
        }

        return () => { tomRef.current?.destroy(); tomRef.current = null; };
    }, [options, value]);

    return <select ref={selectRef} className="form-control" placeholder="Select customer"></select>;
}
