// resources/js/react/Pages/SaleReturn/Components/CustomerDetailsModal.jsx
import React, { useEffect, useState } from "react";
import axios from "axios";

export default function CustomerDetailsModal({ open, onClose, customerId, initialDetails = null, onSaved = null }) {
    const [loading, setLoading] = useState(false);
    const [editing, setEditing] = useState(false);
    const [details, setDetails] = useState(initialDetails);
    const [form, setForm] = useState({ name: "", mobile: "", email: "", whatsapp_mobile: "", company: "", nationality: "", id_no: "" });
    const [errors, setErrors] = useState({});

    useEffect(() => {
        if (!open) return;
        let mounted = true;
        if (initialDetails) {
            setDetails(initialDetails);
            const c = initialDetails.customer || {};
            setForm({
                name: c.name || "",
                mobile: c.mobile || "",
                email: c.email || "",
                whatsapp_mobile: c.whatsapp_mobile || "",
                company: c.company || "",
                nationality: c.nationality || "",
                id_no: c.id_no || "",
            });
            return () => { mounted = false };
        }

        if (!customerId) return;
        setLoading(true);
        axios.get(`/account/customer/${customerId}/details`)
            .then(res => {
                if (!mounted) return;
                if (res.data && res.data.success) {
                    setDetails(res.data);
                    const c = res.data.customer || {};
                    setForm({
                        name: c.name || "",
                        mobile: c.mobile || "",
                        email: c.email || "",
                        whatsapp_mobile: c.whatsapp_mobile || "",
                        company: c.company || "",
                        nationality: c.nationality || "",
                        id_no: c.id_no || "",
                    });
                } else {
                    setDetails(null);
                }
            })
            .catch(() => setDetails(null))
            .finally(() => setLoading(false));

        return () => { mounted = false };
    }, [open, customerId, initialDetails]);

    const save = async () => {
        setErrors({});
        const payload = {
            name: form.name,
            mobile: form.mobile,
            whatsapp_mobile: form.whatsapp_mobile,
            email: form.email,
            company: form.company,
            nationality: form.nationality,
            id_no: form.id_no,
            customer_type_id: details?.customer?.customer_type_id || null,
        };

        try {
            setLoading(true);
            let res;
            if (customerId) {
                res = await axios.put(`/customers/${customerId}`, payload);
            } else {
                res = await axios.post(`/customers`, payload);
            }

            if (res.data && res.data.success) {
                onSaved && onSaved(res.data.customer);
                setEditing(false);
                // refresh details
                setDetails(prev => ({ ...prev, customer: res.data.customer }));
            } else {
                // show generic error
                setErrors({ form: res.data?.message || 'Failed to save' });
            }
        } catch (e) {
            const resp = e.response?.data || {};
            setErrors({ form: resp.message || 'Failed to save' });
        } finally {
            setLoading(false);
        }
    };

    if (!open) return null;

    return (
        <div className="modal fade show d-block" tabIndex="-1" role="dialog">
            <div className="modal-dialog modal-lg" role="document">
                <div className="modal-content">
                    <div className="modal-header">
                        <div>
                            <h5 className="modal-title">Customer Details</h5>
                            <div className="text-muted small">View customer information and history</div>
                        </div>
                        <button type="button" className="btn-close" aria-label="Close" onClick={onClose}></button>
                    </div>
                    <div className="modal-body">
                        {loading && <div>Loading...</div>}

                        {!loading && details && (
                            <div>
                                <div className="card p-3 mb-3">
                                    <div className="d-flex justify-content-between align-items-start">
                                        <div>
                                            <h6 className="mb-1">Basic Information</h6>
                                            <div className="fw-bold">{details.customer.name}</div>
                                            <div className="text-muted small">{details.customer.mobile}{details.customer.email ? ` — ${details.customer.email}` : ''}</div>
                                            <div className="mt-2 text-muted small">
                                                {details.customer.whatsapp_mobile && <div>WhatsApp: {details.customer.whatsapp_mobile}</div>}
                                                {details.customer.company && <div>Company: {details.customer.company}</div>}
                                                {details.customer.id_no && <div>ID: {details.customer.id_no}</div>}
                                            </div>
                                        </div>
                                        <div className="text-end">
                                            <button className="btn btn-sm btn-outline-secondary me-2" onClick={() => setEditing(!editing)}>{editing ? 'Cancel' : 'Edit'}</button>
                                        </div>
                                    </div>
                                </div>

                                {editing && (
                                    <div className="mt-3">
                                        {errors.form && <div className="alert alert-danger">{errors.form}</div>}
                                        <div className="mb-2">
                                            <label className="form-label">Name</label>
                                            <input className="form-control form-control-sm" value={form.name} onChange={(e) => setForm(f => ({ ...f, name: e.target.value }))} />
                                        </div>
                                        <div className="mb-2">
                                            <label className="form-label">Mobile</label>
                                            <input className="form-control form-control-sm" value={form.mobile} onChange={(e) => setForm(f => ({ ...f, mobile: e.target.value }))} />
                                        </div>
                                        <div className="mb-2">
                                            <label className="form-label">WhatsApp</label>
                                            <input className="form-control form-control-sm" value={form.whatsapp_mobile} onChange={(e) => setForm(f => ({ ...f, whatsapp_mobile: e.target.value }))} />
                                        </div>
                                        <div className="mb-2">
                                            <label className="form-label">Email</label>
                                            <input className="form-control form-control-sm" value={form.email} onChange={(e) => setForm(f => ({ ...f, email: e.target.value }))} />
                                        </div>
                                        <div className="mb-2">
                                            <label className="form-label">Company</label>
                                            <input className="form-control form-control-sm" value={form.company} onChange={(e) => setForm(f => ({ ...f, company: e.target.value }))} />
                                        </div>
                                        <div className="mb-2">
                                            <label className="form-label">Nationality</label>
                                            <input className="form-control form-control-sm" value={form.nationality} onChange={(e) => setForm(f => ({ ...f, nationality: e.target.value }))} />
                                        </div>
                                        <div className="mb-2">
                                            <label className="form-label">ID Number</label>
                                            <input className="form-control form-control-sm" value={form.id_no} onChange={(e) => setForm(f => ({ ...f, id_no: e.target.value }))} />
                                        </div>
                                        <div className="d-flex justify-content-end gap-2 mt-2">
                                            <button className="btn btn-secondary btn-sm" onClick={() => setEditing(false)}>Cancel</button>
                                            <button className="btn btn-primary btn-sm" onClick={save} disabled={loading}>{loading ? 'Saving...' : 'Save'}</button>
                                        </div>
                                    </div>
                                )}

                                {!editing && (
                                    <div className="mt-3">
                                        <h6 className="mb-2">Sales Summary</h6>
                                        <div className="d-flex gap-2 mb-3">
                                            <div className="p-2 bg-light rounded flex-fill text-center">
                                                <div className="h4 mb-0">{details.total_sales ?? 0}</div>
                                                <small className="text-muted">Total Sales</small>
                                            </div>
                                            <div className="p-2 bg-light rounded flex-fill text-center">
                                                <div className="h4 mb-0">{details.total_amount ? `₹${Number(details.total_amount).toFixed(2)}` : 'N/A'}</div>
                                                <small className="text-muted">Total Amount</small>
                                            </div>
                                            <div className="p-2 bg-light rounded flex-fill text-center">
                                                <div className="h6 mb-0">{details.last_purchase || 'N/A'}</div>
                                                <small className="text-muted">Last Purchase</small>
                                            </div>
                                        </div>

                                        <h6 className="mb-2">Recent Sales</h6>
                                        <div className="list-group">
                                            {Array.isArray(details.recent_sales) && details.recent_sales.length > 0 ? (
                                                details.recent_sales.map((s) => (
                                                    <div key={s.id} className="list-group-item d-flex justify-content-between align-items-center">
                                                        <div>
                                                            <div className="fw-bold">Sale #{s.invoice_no}</div>
                                                            <div className="text-muted small">{s.date} • {s.items_count ?? s.items?.length ?? 0} items</div>
                                                        </div>
                                                        <div className="text-end">
                                                            <div className="fw-bold">₹{Number(s.total || 0).toFixed(2)}</div>
                                                            <div className="text-muted small">{s.status || ''}</div>
                                                        </div>
                                                    </div>
                                                ))
                                            ) : (
                                                <div className="text-muted">No recent sales found.</div>
                                            )}
                                        </div>
                                    </div>
                                )}
                            </div>
                        )}

                        {!loading && !details && (
                            <div className="text-muted">Customer details not available.</div>
                        )}
                    </div>
                    <div className="modal-footer">
                        <button type="button" className="btn btn-secondary" onClick={onClose}>Close</button>
                    </div>
                </div>
            </div>
        </div>
    );
}

// resources/js/components/CustomerDetailsModal.vue
<template>
    <div v-if="show" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
        @click.self="closeModal">
        <div class="bg-white rounded-lg shadow-xl w-full max-w-4xl mx-4 max-h-[90vh] overflow-hidden" @click.stop>
            <!-- Header -->
            <div
                class="flex items-center justify-between p-4 border-b border-gray-200 bg-gradient-to-r from-purple-50 to-pink-50">
                <div class="flex items-center space-x-3">
                    <div class="p-2 bg-purple-100 rounded-full">
                        <i class="fa fa-user text-purple-600 text-lg"></i>
                    </div>
                    <div>
                        <h3 class="text-lg font-semibold text-gray-900">Customer Details</h3>
                        <p class="text-sm text-gray-600">View customer information and history</p>
                    </div>
                </div>
                <button @click="closeModal"
                    class="p-2 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-full transition-all duration-200">
                    <i class="fa fa-times text-lg"></i>
                </button>
            </div>

            <!-- Content -->
            <div class="p-4 overflow-y-auto max-h-[calc(90vh-8rem)]">
                <div v-if="loading" class="flex items-center justify-center py-8">
                    <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-500"></div>
                    <span class="ml-2 text-gray-600">Loading customer details...</span>
                </div>

                <div v-else-if="customer" class="space-y-6">
                    <!-- Customer Basic Info -->
                    <div class="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-lg p-4 border border-blue-200">
                        <div class="flex items-center justify-between mb-4">
                            <h4 class="text-lg font-semibold text-gray-800 flex items-center">
                                <i class="fa fa-user-circle mr-2 text-blue-600"></i>
                                Basic Information
                            </h4>
                            <button @click="editCustomer"
                                class="bg-blue-500 text-white px-3 py-1 rounded-md text-sm hover:bg-blue-600 transition-colors">
                                <i class="fa fa-edit mr-1"></i>Edit
                            </button>
                        </div>

                        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <label class="text-xs font-medium text-gray-600">Full Name</label>
                                <p class="text-sm font-semibold text-gray-800">{{ customer.name }}</p>
                            </div>
                            <div>
                                <label class="text-xs font-medium text-gray-600">Mobile</label>
                                <p class="text-sm font-semibold text-gray-800">
                                    <i class="fa fa-phone mr-1 text-green-500"></i>
                                    {{ customer.mobile }}
                                </p>
                            </div>
                            <div v-if="customer.email">
                                <label class="text-xs font-medium text-gray-600">Email</label>
                                <p class="text-sm font-semibold text-gray-800">
                                    <i class="fa fa-envelope mr-1 text-blue-500"></i>
                                    {{ customer.email }}
                                </p>
                            </div>
                            <div v-if="customer.whatsapp_mobile">
                                <label class="text-xs font-medium text-gray-600">WhatsApp</label>
                                <p class="text-sm font-semibold text-gray-800">
                                    <i class="fa fa-whatsapp mr-1 text-green-500"></i>
                                    {{ customer.whatsapp_mobile }}
                                </p>
                            </div>
                            <div v-if="customer.company">
                                <label class="text-xs font-medium text-gray-600">Company</label>
                                <p class="text-sm font-semibold text-gray-800">
                                    <i class="fa fa-building mr-1 text-orange-500"></i>
                                    {{ customer.company }}
                                </p>
                            </div>
                            <div v-if="customer.nationality">
                                <label class="text-xs font-medium text-gray-600">Nationality</label>
                                <p class="text-sm font-semibold text-gray-800">
                                    <i class="fa fa-flag mr-1 text-red-500"></i>
                                    {{ customer.nationality }}
                                </p>
                            </div>
                        </div>
                    </div>

                    <!-- Sales Summary -->
                    <div class="bg-gradient-to-r from-green-50 to-emerald-50 rounded-lg p-4 border border-green-200">
                        <h4 class="text-lg font-semibold text-gray-800 mb-4 flex items-center">
                            <i class="fa fa-chart-line mr-2 text-green-600"></i>
                            Sales Summary
                        </h4>

                        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                            <div class="text-center p-3 bg-white rounded-lg border border-green-200">
                                <div class="text-2xl font-bold text-green-600">{{ totalSales || 0 }}</div>
                                <div class="text-xs text-gray-600">Total Sales</div>
                            </div>
                            <div class="text-center p-3 bg-white rounded-lg border border-green-200">
                                <div class="text-2xl font-bold text-blue-600">{{ totalAmount || 0 }}</div>
                                <div class="text-xs text-gray-600">Total Amount</div>
                            </div>
                            <div class="text-center p-3 bg-white rounded-lg border border-green-200">
                                <div class="text-2xl font-bold text-purple-600">{{ lastPurchase || 'N/A' }}</div>
                                <div class="text-xs text-gray-600">Last Purchase</div>
                            </div>
                        </div>
                    </div>

                    <!-- Recent Sales -->
                    <div v-if="recentSales.length > 0" class="bg-gradient-to-r from-purple-50 to-pink-50 rounded-lg p-4 border border-purple-200">
                        <h4 class="text-lg font-semibold text-gray-800 mb-4 flex items-center">
                            <i class="fa fa-history mr-2 text-purple-600"></i>
                            Recent Sales
                        </h4>

                        <div class="space-y-2">
                            <div v-for="sale in recentSales" :key="sale.id"
                                class="bg-white rounded-lg p-3 border border-purple-200 hover:shadow-md transition-shadow">
                                <div class="flex justify-between items-center">
                                    <div>
                                        <div class="font-semibold text-sm text-gray-800">
                                            Sale #{{ sale.invoice_no }}
                                        </div>
                                        <div class="text-xs text-gray-600">
                                            {{ sale.date }} • {{ sale.items_count }} items
                                        </div>
                                    </div>
                                    <div class="text-right">
                                        <div class="font-bold text-sm text-green-600">
                                            ₹{{ sale.total }}
                                        </div>
                                        <div class="text-xs text-gray-500">
                                            {{ sale.status }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- No Recent Sales -->
                    <div v-else class="bg-gradient-to-r from-gray-50 to-slate-50 rounded-lg p-4 border border-gray-200">
                        <div class="text-center py-4">
                            <i class="fa fa-shopping-cart text-4xl text-gray-400 mb-2"></i>
                            <h4 class="text-lg font-semibold text-gray-600">No Recent Sales</h4>
                            <p class="text-sm text-gray-500">This customer hasn't made any purchases yet.</p>
                        </div>
                    </div>
                </div>

                <div v-else class="text-center py-8">
                    <i class="fa fa-exclamation-triangle text-4xl text-gray-400 mb-2"></i>
                    <h4 class="text-lg font-semibold text-gray-600">Customer Not Found</h4>
                    <p class="text-sm text-gray-500">Unable to load customer details.</p>
                </div>
            </div>

            <!-- Footer -->
            <div class="flex items-center justify-end space-x-3 p-4 border-t border-gray-200 bg-gradient-to-r from-gray-50 to-blue-50">
                <button type="button" @click="closeModal"
                    class="flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 transition-all duration-200 shadow-sm hover:shadow-md">
                    <i class="fa fa-times mr-2 text-gray-500"></i>
                    Close
                </button>
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref, watch } from 'vue'
import { useToast } from 'vue-toastification'

const props = defineProps({
    show: {
        type: Boolean,
        default: false
    },
    customerId: {
        type: [String, Number],
        default: null
    }
})

const emit = defineEmits(['close', 'edit'])

const toast = useToast()
const loading = ref(false)
const customer = ref(null)
const totalSales = ref(0)
const totalAmount = ref(0)
const lastPurchase = ref(null)
const recentSales = ref([])

const closeModal = () => {
    emit('close')
}

const editCustomer = () => {
    emit('edit', customer.value)
}

const loadCustomerDetails = async () => {
    if (!props.customerId) return

    loading.value = true
    try {
        const response = await axios.get(`/account/customer/${props.customerId}/details`)
        customer.value = response.data.customer
        totalSales.value = response.data.total_sales || 0
        totalAmount.value = response.data.total_amount || 0
        lastPurchase.value = response.data.last_purchase || null
        recentSales.value = response.data.recent_sales || []
    } catch (error) {
        toast.error('Failed to load customer details')
        console.error('Error loading customer details:', error)
    } finally {
        loading.value = false
    }
}

// Watch for changes in customerId and show prop
watch(() => [props.customerId, props.show], ([newCustomerId, newShow]) => {
    if (newShow && newCustomerId) {
        loadCustomerDetails()
    }
}, { immediate: true })
</script>
